M48
; DRILL file {KiCad (6.0.2)} date Thu Jul  7 22:01:22 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-07T22:01:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X50.0Y-48.0
X112.0Y-48.0
X112.0Y-93.0
T2
X52.0Y-51.75
X110.0Y-51.75
T0
M30
